/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SDA_1_aliases.h>
#include <SDA_1.h>
#include <SCL_1_aliases.h>
#include <SCL_1.h>
#include <psoc.h>
#include <psoc_PVT.h>
#include <UART_Wind.h>
#include <isr_Wind.h>
#include <UART_SBD.h>
#include <SBD_reply.h>
#include <master.h>
#include <master_PVT.h>
#include <clock.h>
#include <dataPin_aliases.h>
#include <dataPin.h>
#include <selectPin_aliases.h>
#include <selectPin.h>
#include <clockPin_aliases.h>
#include <clockPin.h>
#include <EEPROM.h>
#include <UART_Wind_IntClock.h>
#include <UART_SBD_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

