/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Thermocouple_1.h>
#include <ADC_DelSig.h>
#include <AMux.h>
#include <Thermocouple_Pos_aliases.h>
#include <Thermocouple_Pos.h>
#include <Thermocouple_Neg_aliases.h>
#include <Thermocouple_Neg.h>
#include <SDA_1_aliases.h>
#include <SDA_1.h>
#include <SCL_1_aliases.h>
#include <SCL_1.h>
#include <psoc.h>
#include <psoc_PVT.h>
#include <LCD.h>
#include <ADC_DelSig_Ext_CP_Clk.h>
#include <ADC_DelSig_IRQ.h>
#include <ADC_DelSig_theACLK.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

